import Head from 'next/head'
import type { AppProps } from 'next/app'
import { AuthProvider } from '../services/AuthContext';
import 'bootstrap/dist/css/bootstrap.css';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<AuthProvider>
				<Head>
					<title>Lobo Adoção De Animais</title>
					<meta name="Site de adoção de animais Lobo" content="Generated by next app" />
					<link rel="icon" href="favicon.ico" type="image/x-icon" />
				</Head>
				<Navbar />
				<Component {...pageProps} />
				<Footer />
			</AuthProvider>
		</>
	);
}

export default MyApp;